# Generated by Django 6.0.3 on 2026-04-28 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_secretversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretversion',
            name='secret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='core.secret'),
        ),
    ]
